//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalInfo
    {
        public int HospitalInfoId { get; set; }
        public string DocName { get; set; }
        public string Addresss { get; set; }
        public string MobileNO { get; set; }
        public int SpecialistDocId { get; set; }
        public int HospitalsId { get; set; }
        public string Email { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual SpecialistDoc SpecialistDoc { get; set; }
    }
}
