//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPHCESchme
    {
        public int NPHCESchmeId { get; set; }
        public string FullName { get; set; }
        public int MarritalStatusId { get; set; }
        public int GenderId { get; set; }
        public System.DateTime DOB { get; set; }
        public string BankBranch { get; set; }
        public string BankAccNo { get; set; }
        public string AadharNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Age { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MarritalStatu MarritalStatu { get; set; }
    }
}
