//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserInfoId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PassWd { get; set; }
        public string MobileNO { get; set; }
        public string Email { get; set; }
        public System.DateTime DOB { get; set; }
        public int GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
