//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public int VaccinationId { get; set; }
        public string Adresss { get; set; }
        public int CityId { get; set; }
        public int StatesId { get; set; }
        public int LocalityId { get; set; }
        public int CountryId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Locality Locality { get; set; }
    }
}
